### PR TITLE
Remove monorepo and ARIA Practices from aria-common deploy

### PR DESCRIPTION
**Pull request by daniel-montalvo**

### CODE REVIEW

**Review by pkra — DISMISSED** [review]
Looks good to me. but I'm guessing a review from @mcking65  or @nschonni is more relevant :smiley:

**Comment by nschonni** [comment]
Sorry, I haven't been tracking what's happening over in that repo much. Maybe @howard-e would be better to give a thumbs up than me.

**Comment by daniel-montalvo** [comment]
Thanks @nschonni  @pkra  @howard-e
This is a request from @mcking65 . Just mentioning him as well so that he knows this is in progress.

**Comment by pkra** [comment]
@daniel-montalvo I was about to make a PR that removes all ARIA specs from automation (now that the monorepo is up and running). Should we update this one instead?

**Comment by daniel-montalvo** [comment]
@pkra 

I'll update this.

**Review by pkra — APPROVED** [review]

**Pull request merged**
