### PR TITLE
Fix auto exporting and add missing IDs back to mapping tables

### PR DESCRIPTION
**Pull request by spectranaut**
This is regard to: https://github.com/w3c/core-aam/issues/102
PR reviewed originally here: https://github.com/w3c/core-aam/pull/105

Changes:
- Table ids are back!
- The "saved"/"exported" spec to use the summary details instead of the table. 
- Removed the dependencies on respec events as in the issue it was discussed repub no longer publishes events. It turns out that the "mappingTables" function is called during respect "preprocessing" (as was configured in the preProcess parameter in the respecConfig), so once i removed the respec events code -- which was causing an error -- the tables showed up twice (as mappingTables was run twice, once during preprocessing and once when mapping-tables.js was loaded).
- @michael-n-cooper fixed a bug in the show/hide columns buttons in the table view

### CODE REVIEW

**Comment by spectranaut** [comment]
Hi @michael-n-cooper if you are good with this change can you merge? :) James will be out for the next week.

**Comment by spectranaut** [comment]
maybe @jnurthen is back from vacation? :)

**Comment by jnurthen** [comment]
crossing fingers

**Comment by stevefaulkner** [comment]
> Table ids are back!

thanks for fixing this, has been annoying me ;-)

**Comment by jnurthen** [comment]
Is it working. It is not for me right now.
________________________________

**Comment by stevefaulkner** [comment]
@jnurthen i am still seeing `<summary id="">` in [html-aam](https://w3c.github.io/html-aam/)

**Comment by jnurthen** [comment]
Not surprising in html-aam as that isn't using the common version right now. 

It is still broken in core-aam for me though. Looking into it.

**Comment by spectranaut** [comment]
I can look at it tomorrow if you don't get any where @jnurthen!

**Comment by jnurthen** [comment]
I'm making progress... give me another day or so.

**Pull request merged**
